export {default as Facebook} from "./facebook.svg"
export {default as Instagram} from "./instagram.svg"
export {default as Linkdin } from "./linkdin.svg"
export { default as Twitter } from "./twitter.svg"
//our service
export { default as Booking } from "./our_services/Bookings.png"
export { default as BrandPartner} from "./our_services/brand_partner.png"
export { default as LabelService} from "./our_services/label_service.png"
export { default as Management} from "./our_services/socialmedia_management.png"
export { default as Talent} from "./our_services/Talent_management.png"
export { default as PR} from "./our_services/PR.png"
//our service2
export { default as Booking2 } from "./booking2.png"
export { default as Booking3 } from "./booking3.png"
export { default as BrandPartner2} from "./our_services2/BrandPartner.png"
export { default as LabelService2} from "./our_services2/label.png"
export { default as Management2} from "./our_services2/Social.png"
export { default as Talent2} from "./our_services2/Talent.png"
export { default as PR2} from "./our_services2/PR.png"
export { default as About} from "./aboutus.jpg"
export { default as News} from "./news.png"
export { default as PostedNews} from "./newscards/posted_news.png"
export { default as ManReading} from "./newscards/man_reading.png"
export { default as Phone} from "./newscards/phone.png"
export {default as LiveBands} from "./book fav/live band.png"
export {default as DJS} from "./book fav/DJS.png"
export {default as Musicians} from "./book fav/musicians.png"
export {default as Comedians} from "./book fav/comedians.png"
export {default as MCS} from "./book fav/MCS.png"
export {default as Influencers} from "./book fav/influencers.png"
export {default as Band1} from "./book band/1.png"
export {default as Band2} from "./book band/2.png"
export {default as Band3} from "./book band/3.png"
export {default as BookMusician} from "./book musician/1.png"
export {default as BookMc} from "./book mc/1.png"
export {default as BookDj} from "./book dj/1.png"
export {default as BookInfluencer} from "./book influencer/1.png"
export {default as BookComedian} from "./book comedian/1.png"

export {default as Star} from "./Star.png"
export { default as Social} from "./our_services2/Social.png"
export { default as Label} from "./our_services2/label.png"
export { default as Coporate2} from "./our_services2/coporate_entertainment.png"
export { default as PrivateParties2} from "./our_services2/private_parties.png"
export { default as Celeb2} from "./our_services2/celeb_appearance.png"
export { default as Concerts2} from "./our_services2/concert.png"
export { default as Fairs2} from "./our_services2/fairs.png"
export { default as Birthday2} from "./our_services2/birthday.png"
export { default as Wedding2} from "./our_services2/wedding_entertainment.png"
export { default as Coporate} from "./our_services/coperate_entertainment.png"
export { default as Birthday} from "./our_services/birthday.png"
export { default as Celeb} from "./our_services/celeb-appearance.png"
export { default as Fairs} from "./our_services/fairs.png"
export { default as PrivateParties} from "./our_services/private_parties.png"
export { default as Concerts} from "./our_services/public_concert.png"
export { default as Wedding} from "./our_services/weddding.png"
export {default as FB} from "./book band/fb.svg";
export {default as Twitter2} from "./book band/twitter.svg";
export {default as Insta} from "./book band/insta.svg";
export {default as BandInfo} from "./artist info/band.png";
export {default as ComedianInfo} from "./artist info/comedian.png";
export {default as DjInfo} from "./artist info/Dj.png";
export {default as InfluencerInfo} from "./artist info/influencer.png";
export {default as McInfo} from "./artist info/mc.png";
export {default as MusicianInfo} from "./artist info/musician.png";
export {default as CloseList} from "./closedrop_btn.svg"
export {default as ExploreBand} from "./explore images/live band.png"
export {default as ExploreMusician} from "./explore images/musician.png"
export {default as ExploreComedian} from "./explore images/comedian.png"
export {default as ExploreDjs} from "./explore images/djs.png"
export {default as Cheers} from "./cheercrowd.png"
export {default as two} from "./2.png"
export {default as three} from "./3.png"
export {default as four} from "./4.png"
export {default as five} from "./5.png"
export {default as one} from "./1.png"
export {default as viewingLappy} from "./lappy.png"
export {default as Chairs} from "./chairs.png"
export {default as Piano} from "./piano.png"
export {default as MoreBirthday} from "./learn more/birthday.png"
export {default as MoreCeleb} from "./learn more/celeb_appearance.png"
export {default as MoreConcert} from "./learn more/concert.png"
export {default as MoreCoporate} from "./learn more/coporate.png"
export {default as MoreFairs} from "./learn more/fairs.png"
export {default as MorePrivate} from "./learn more/private.png"
export {default as MoreWedding} from "./learn more/wedding.png"

export {default as Marquee1} from "./marquee/1.png"
export {default as Marquee2} from "./marquee/2.png"
export {default as Marquee3} from "./marquee/3.png"
export {default as Marquee4} from "./marquee/4.png"
export {default as Marquee5} from "./marquee/5.png"
export {default as Marquee6} from "./marquee/6.png"

export {default as wizkid} from "./search artist/wizkid.jpg"
export {default as burnaboy} from "./search artist/burnaboy.jpg"
export {default as davido} from "./search artist/davido.jpg"
export {default as donjazzy} from "./search artist/donjazzy.jpg"
export {default as flavour} from "./search artist/flavour.jpg"
export {default as nasty_c} from "./search artist/nasty_c.jpg"
export {default as olamide} from "./search artist/olamide.jpg"
export {default as phyno} from "./search artist/phyno.jpg"
export {default as psquare} from "./search artist/psquare.jpg"
export {default as tems} from "./search artist/tems.jpg"
export {default as yemi_alade} from "./search artist/yemi_alade.jpg"
export {default as buju} from "./search artist/buju.jpg"


