export {default as Facebook} from "./facebook.svg"
export {default as Instagram} from "./instagram.svg"
export {default as Linkdin } from "./linkdin.svg"
export { default as Twitter } from "./twitter.svg"
export { default as Booking } from "./our_services/Bookings.png"
export { default as BrandPartner} from "./our_services/brand_partner.png"
export { default as LabelService} from "./our_services/label_service.png"
export { default as Management} from "./our_services/socialmedia_management.png"
export { default as Talent} from "./our_services/Talent_management.png"
export { default as PR} from "./our_services/PR.png"