export {default as Facebook} from "./facebook.svg"
export {default as Instagram} from "./instagram.svg"
export {default as Linkdin } from "./linkdin.svg"
export { default as Twitter } from "./twitter.svg"
//our service
export { default as Booking } from "./our_services/Bookings.png"
export { default as BrandPartner} from "./our_services/brand_partner.png"
export { default as LabelService} from "./our_services/label_service.png"
export { default as Management} from "./our_services/socialmedia_management.png"
export { default as Talent} from "./our_services/Talent_management.png"
export { default as PR} from "./our_services/PR.png"
//our service2
export { default as Booking2 } from "./our_services2/Booking.png"
export { default as BrandPartner2} from "./our_services2/BrandPartner.png"
export { default as LabelService2} from "./our_services2/label.png"
export { default as Management2} from "./our_services2/Social.png"
export { default as Talent2} from "./our_services2/Talent.png"
export { default as PR2} from "./our_services2/PR.png"
export { default as Social} from "./our_services2/Social.png"
export { default as Label} from "./our_services2/label.png"