export { default as Nav } from "./nav/Nav";
export { default as Footer } from "./footer/Footer";
export { default as Booking } from "./booking/Booking";
export { default as SignUp } from "./sign-up/SIgnUp";
export { default as OurService } from "./our-services/OurServices";
export { default as OurServices2 } from "./our-service2/OurServices2";
export { default as NewsGallery} from "./news card gallery/NewsGallery";
export { default as Book} from "./Book/Book";
export { default as Explore} from "./explore/Explore";
export { default as OurVision} from "./OurVision/OurVision";
export { default as OurMission} from "./OurMission/OurMission";
export { default as BannerSlider} from "./bannerSlider/BannerSlider";
